# Generated by Django 5.0.1 on 2024-02-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_room_attendant_message_username_agentprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='agents',
        ),
        migrations.DeleteModel(
            name='AgentProfile',
        ),
    ]
