# Generated by Django 5.0.1 on 2024-02-07 02:01

import Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='qid',
            field=models.CharField(default=Base.models.generate_random_qid, max_length=20),
        ),
    ]
